using AkshaySDemoModels.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace AkshaySDemoPostgreSQL.Data
{
    public class AkshaySDemoPostgreSQLContext : DbContext
    {
        public static string ConnectionString { get; set; }
        
        internal virtual DbSet<Recipe> Recipes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if(!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql(ConnectionString);
            }
        }
    }
}

/*
PostgreSQL akshaysdemodb
------------------------
CREATE TABLE recipes(
	ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Name varchar(256) NULL,
	Description varchar(512) NULL,
	Comment varchar(1024) NULL,
	CreatorsName varchar(256) NULL,
	Notes varchar(5000) NULL
)
*/
